import combined_modulation_schemes_trellis_codes_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace combined_modulation_schemes_trellis_codes_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end combined_modulation_schemes_trellis_codes_theorem_canonical_lane_mathlib
end HautevilleHouse
